name: Tests
on: [push, pull_request]
env:
    MAVEN_OPTS: "-XX:CompressedClassSpaceSize=256m -XX:+UseSerialGC -Xmx2g -XX:MaxMetaspaceSize=512m"    
jobs:
    unit-tests:
        runs-on: ubuntu-18.04
        name: Unit Tests on Latest ASF Versions
        env:
            IT_ONLY: false
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up JDK 1.8
              uses: joschi/setup-jdk@v2
              with:
                java-version: '8'  
                architecture: x64  

            - name: Set up Maven
              uses: stCarolas/setup-maven@v4
              with:
                maven-version: 3.6.3
                
            - name: Cache maven resources
              uses: actions/cache@v2
              env:
                cache-name: cache-maven-resources
              with:
                key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                      ${{ runner.os }}-mvn-
                path: |
                      ~/.m2/repository

            - name: Cache other resources
              uses: actions/cache@v2
              env:
                cache-name: cache-resources
              with:
                key: ${{ runner.os }}-other
                restore-keys: |
                      ${{ runner.os }}-other
                path: |  
                      ~/.downloads
                      test/target/temp/gdal

            - name: Run
              run: mvn verify
                     
    